exports.classes = [
  {
    title: "Linguistics",
    subject: "English",
    instructor: "Henry Collier",
    difficulty: 7,
    enrollees: [],
  },
  {
    title: "Philosophy",
    subject: "Arts",
    instructor: "Linda Bryant",
    difficulty: 6,
    enrollees: [],
  },
  {
    title: "Algebra 101",
    subject: "Math",
    instructor: "Emilio Byrd",
    difficulty: 3,
    enrollees: [],
  },
  {
    title: "Intro to Calculus",
    subject: "Math",
    instructor: "Dawn Payne",
    difficulty: 9,
    enrollees: [],
  },
  {
    title: "Computer Science",
    subject: "Science",
    instructor: "Maxine Maldonado",
    difficulty: 5,
    enrollees: [],
  },
  {
    title: "Organic Chemistry",
    subject: "Science",
    instructor: "Robyn Curtis",
    difficulty: 8,
    enrollees: [],
  },
  {
    title: "English 101",
    subject: "English",
    instructor: "Brett Perry",
    difficulty: 2,
    enrollees: [],
  },
  {
    title: "Film Studies",
    subject: "Art",
    instructor: "Alicia Maldonado",
    difficulty: 1,
    enrollees: [],
  },
  {
    title: "Quantam Physics",
    subject: "Science",
    instructor: "Laurence Mcdaniel",
    difficulty: 10,
    enrollees: [],
  },
];
