exports.classes = [
  {
    title: "Linguistics",
    subject: "English",
    instructor: {
      name: "Henry Collier",
      image: "https://i.imgur.com/iS057KG.png",
      email: "hcollier@uni.edu",
      phone: "202-555-0102",
    },
    difficulty: 7,
    enrollees: [],
  },
  {
    title: "Philosophy",
    subject: "Arts",
    instructor: {
      name: "Linda Bryant",
      image: "https://i.imgur.com/KvHjhi5.png",
      email: "lbryant@uni.edu",
      phone: "202-555-0103",
    },
    difficulty: 6,
    enrollees: [],
  },
  {
    title: "Algebra 101",
    subject: "Math",
    instructor: {
      name: "Emilio Byrd",
      image: "https://i.imgur.com/N5VvDyV.png",
      email: "ebyrd@uni.edu",
      phone: "202-555-0104",
    },
    difficulty: 3,
    enrollees: [],
  },
  {
    title: "Intro to Calculus",
    subject: "Math",
    instructor: {
      name: "Dawn Payne",
      image: "https://i.imgur.com/UoW08s5.png",
      email: "dpayne@uni.edu",
      phone: "202-555-0105",
    },
    difficulty: 9,
    enrollees: [],
  },
  {
    title: "Computer Science",
    subject: "Science",
    instructor: {
      name: "Maxine Maldonado",
      image: "https://i.imgur.com/0jgdNII.png",
      email: "mmaldonado@uni.edu",
      phone: "202-555-0106",
    },
    difficulty: 5,
    enrollees: [],
  },
  {
    title: "Organic Chemistry",
    subject: "Science",
    instructor: {
      name: "Robyn Curtis",
      image: "https://i.imgur.com/TVFaWSk.png",
      email: "rcurtis@uni.edu",
      phone: "202-555-0107",
    },
    difficulty: 8,
    enrollees: [],
  },
  {
    title: "English 101",
    subject: "English",
    instructor: {
      name: "Brett Perry",
      image: "https://i.imgur.com/oMocLKR.png",
      email: "bperry@uni.edu",
      phone: "202-555-0108",
    },
    difficulty: 2,
    enrollees: [],
  },
  {
    title: "Film Studies",
    subject: "Art",
    instructor: {
      name: "Alicia Maldonado",
      image: "https://i.imgur.com/rlkg0Ga.png",
      email: "amaldonado@uni.edu",
      phone: "202-555-0109",
    },
    difficulty: 1,
    enrollees: [],
  },
  {
    title: "Quantam Physics",
    subject: "Science",
    instructor: {
      name: "Laurence Mcdaniel",
      image: "https://i.imgur.com/0sAW3ts.png",
      email: "lmcdaniel@uni.edu",
      phone: "202-555-0110",
    },
    difficulty: 10,
    enrollees: [],
  },
];

// name: String,
// image: String,
// email: String,
// phone: Number,
